config/routes.rb
StreamDB::Application.routes.draw do
  get "users/new"
  get "users/create"
  post "users/login"
  root 'streams#index'
  get 'streams/stream_list' => 'streams#stream_list'
  get 'streams/play/:stream_id' => 'streams#track_play'
  get 'streams/update' => 'streams#update_streams'
  get 'robot' => 'robot#index'
  post 'robot/start_scraping' => 'robot#start_scraping'

end

app/models/play.rb
class Play < ActiveRecord::Base

  belongs_to :video
  belongs_to :user

  validates_uniqueness_of :user_id, scope: :video_id

  def self.by(user)
    find_by_user_id(user) || None.new
  end

  after_initialize do
    # does this even work?
    # todo: move default to db
    if self.new_record?
      self.play_count = 0
    end
  end

  class None
    attr_accessor :play_count

    def initialize
      @play_count = 0
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  
end

app/models/video.rb
require 'robot'

class Video < ActiveRecord::Base

  attr_accessor :play_count, :new

  validates_presence_of :title, :post_date, :post_url, :thumbnail, :sport
  validate :unique_urls

  has_many :plays

  scope :recent, ->(sport) { where(sport: sport).order('created_at DESC').first(40) }

  def self.update(*sports)
    Robot.scrape(*sports)
  end

private

  def unique_urls
    count = 0
    count += Video.where(:direct_url => direct_url).count if direct_url
    count += Video.where(:post_url => post_url).count if post_url
    errors.add(:base, 'URL already exists') unless count.zero?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def login(user)
    session[:user_id] = user.id
    set_current_user
  end

  def user_logged_in?
    session[:user_id].present? && @current_user
  end

  def set_current_user
    @current_user = User.find_by_id(session[:user_id])
    @current_user ||= GuestUser.new(1, 'Guest')
  end

  def logout_user
    @current_user, session[:user_id] = nil, nil
  end

  GuestUser = Struct.new(:id, :username)
end

app/controllers/robot_controller.rb
class RobotController < ApplicationController
  def index

  end

  def start_scraping
  end
end

app/controllers/streams_controller.rb
class StreamsController < ApplicationController
  before_filter :set_current_user

  def index
  end

  def stream_list
    render json: {
      new_streams: new_streams,
      old_streams: old_streams
    }
  end

  def track_play
    stat = Play.find_or_initialize_by(user_id: @current_user.id, video_id: params[:stream_id])
    stat.play_count = (stat.play_count || 0) + 1
    stat.save
    render json: stat
  end

  def update_streams
    UpdateStreams.new.async.perform([:snow, :skate, :surf])
    #UpdateStreams.new.perform([:snow, :skate, :surf])

    render json: {
      queued: 'Snow, skate, and surf videos are being updated'
    }
  end

private

  def sports_list
    ['snow', 'skate', 'surf']
  end

  def new_streams
    recent_streams = sports_list.each_with_object({}) do |sport, hsh|
      hsh[sport] = Video.recent(sport)
    end

    plays = Play.where(user_id: @current_user.id, video_id: recent_streams.values.flatten)
    plays = plays.pluck(:video_id, :play_count).each_with_object({}) do |(video_id, play_count), hsh|
      hsh[video_id] = play_count
    end

    recent_streams.each do |sport, streams|
      recent_streams[sport] = streams.map do |stream|
        s = stream.attributes.merge({
          play_count: plays.fetch(stream.id) { 0 },
          url: stream['direct_url'] || stream['post_url']
        })

        s[:play_count] == 0 ? s : nil
      end.compact
    end
  end

  def old_streams
    arr   = Play.where(user_id: @current_user.id).pluck(:video_id, :play_count)
    plays = arr.each_with_object({}) do |(video_id, play_count), hsh|
      hsh[video_id] = play_count
    end

    streams = Video.where(id: plays.keys).map(&:attributes)
    streams.each do |stream|
      stream['play_count'] = plays[stream['id']]
      stream['url']        = stream['direct_url'] || stream['post_url']
    end

    streams.group_by do |stream|
      stream['sport']
    end
  end

  def plays_by_user(streams)
    Play.where(user_id: @current_user.id, video_id: (streams))
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      session[:user_id] = @user.id
    else
      flash[:error] = @user.errors
    end

    render 'new'
  end

  def login
    @user = User.authenticate(params[:username], [:password])
    if @user
      session[:user_id] = @user.id
    else
      render('streams')
    end
  end

  def logout
    @current_user = nil    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/robot_helper.rb
module RobotHelper
end

app/helpers/streams_helper.rb
module StreamsHelper
  def new?(stream)
    stream.plays_by(@current_user) == 0 ? 'new' : ''
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!! 5
%html{ :'ng-app' => 'streamsApp' }
%head
  %title StreamDB
  = stylesheet_link_tag :'application', media: 'all', :'data-turbolinks-track' => true
  = javascript_include_tag :'application', :'data-turbolinks-track' => true
  = csrf_meta_tags
%body{ :'ng-controller' => 'StreamsListCtrl' }
  = yield

app/views/robot/index.html.haml
%h2 Robot

= form_tag robot_start_scraping_path do
  = label :scrape, 'TransworldSnow'
  = check_box_tag :scrape, :TransworldSnow
  = label :scrape, 'SnowboarderMag'
  = check_box_tag :scrape, :sbm
  %br
  = submit_tag 'Save Changes'

app/views/streams/_cube_face.haml
%section.sport{ style: "background-image: url(assets/#{background})" }
  #overlay
  .page
    %ul.new_streams
      %li{ :'ng-repeat' => "stream in newStreams['#{sport}'] | limitTo: (currentPage['#{sport}'] * 7) + 7 | limitTo: -7", :'ng-style' => "{ background: 'url(\"{{stream.thumbnail}}\") 100% center' }" }
        %a{ :href => "{{stream.url}}", :'ng-click' => "trackPlay()", :target => '_blank' }
          %p.details
            %span.title {{stream.title}}
            %br
            %span.play_count {{stream.play_count}}
    %ul.old_streams
      %li{ :'ng-repeat' => "stream in oldStreams['#{sport}']" }
        %a{ :href => "{{stream.url}}", :'ng-click' => "trackPlay()", :target => '_blank', :'ng-style' => "{ 'background-image': 'url(\"{{stream.thumbnail}}\")' }" }
        %span (-) {{stream.play_count}}
        %a{ :href => "{{stream.post_url}}" }
          %p {{stream.title}}

    = render('page_controls', :sport => sport)

app/views/streams/_page_controls.html.haml
%button{ :class => 'page_back', :'ng-click' => "pageBack('#{sport}')" }
%button{ :class => 'page_forward', :'ng-click' => "pageForward('#{sport}')" }

app/views/streams/index.html.haml
-#%a{ :id => "update" } Update

-# - if @current_user.username == 'Guest'
-#   -# render('users/create')
-#   = render('users/login')

#contols
  #p2
    Skate
  #p1
    Snow
  #p3
    Surf

#cube
  #f3
    = render('cube_face', sport: 'surf', background: 'bkg_surf_1_resize.jpg')
  #f2
    = render('cube_face', sport: 'skate', background: 'bkg_skate_1_resize.jpg')
  #f1
    = render('cube_face', sport: 'snow', background: 'bkg_snow_1_resize.jpg')

app/views/users/_create.html.haml
#darken
  = form_tag(users_create_path, class: 'create') do
    %a.show_form
    #create_form
      = label_tag 'Username: '
      = text_field_tag 'user[username]'
      = label_tag 'Email: '
      = text_field_tag 'user[email]'
      = label_tag 'Password: '
      = password_field_tag 'user[password]'
      = submit_tag 'Create Account'

app/views/users/_login.html.haml
= form_tag(users_login_path, class: 'login') do
  %a.show_form
  #login_form
    = label_tag 'Username:'
    = text_field_tag 'user[username]'
    = label_tag 'Password:'
    = password_field_tag 'user[password]'
    = submit_tag 'Login'